// Netflix Catalog Data with high-fidelity backdrops, posters, cast, and video streams
export const catalog = [
  {
    id: "stranger-things",
    title: "Stranger Things",
    type: "series",
    logoTitle: "STRANGER THINGS",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    matchScore: 99,
    rating: "16+",
    releaseYear: 2024,
    seasons: 4,
    seasonsCount: 4,
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos 5.1",
    isTop10: 1,
    isTrending: true,
    isPopular: true,
    genres: ["Sci-Fi", "Mystery", "Supernatural", "Teen Drama"],
    tags: ["Mind-bending", "Ominous", "Nostalgic"],
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour", "Gaten Matarazzo"],
    creator: "The Duffer Brothers",
    episodes: [
      {
        id: "st-s1e1",
        season: 1,
        number: 1,
        title: "Chapter One: The Vanishing of Will Byers",
        duration: "49m",
        overview: "On his way home from a friend's house, young Will sees something terrifying. Nearby, a sinister secret lurks in the depths of a government lab.",
        thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80"
      },
      {
        id: "st-s1e2",
        season: 1,
        number: 2,
        title: "Chapter Two: The Weirdo on Maple Street",
        duration: "56m",
        overview: "Lucas, Mike and Dustin try to talk to the girl they found in the woods. Chief Hopper questions an anxious Joyce about an unsettling phone call.",
        thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80"
      },
      {
        id: "st-s1e3",
        season: 1,
        number: 3,
        title: "Chapter Three: Holly, Jolly",
        duration: "52m",
        overview: "An increasingly frantic Joyce believes Will is communicating with her through holiday lights. The boys test Eleven's abilities.",
        thumbnail: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=500&q=80"
      },
      {
        id: "st-s1e4",
        season: 1,
        number: 4,
        title: "Chapter Four: The Body",
        duration: "51m",
        overview: "Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover before taking her to school.",
        thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=500&q=80"
      }
    ]
  },
  {
    id: "cyberpunk-edgerunners",
    title: "Cyberpunk: Edgerunners",
    type: "series",
    logoTitle: "CYBERPUNK EDGERUNNERS",
    backdrop: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    matchScore: 98,
    rating: "18+",
    releaseYear: 2023,
    seasons: 1,
    seasonsCount: 1,
    resolution: "4K Ultra HD",
    audio: "Spatial Audio",
    isTop10: 2,
    isTrending: true,
    isPopular: true,
    genres: ["Anime", "Action", "Cyberpunk", "Sci-Fi"],
    tags: ["Gritty", "Futuristic", "Explosive"],
    overview: "A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner: a mercenary outlaw also known as a cyberpunk.",
    cast: ["KENN", "Aoi Yuki", "Hiroki Touchi", "Michiko Kaiden"],
    creator: "Rafal Jaki, Studio Trigger",
    episodes: [
      {
        id: "cp-e1",
        season: 1,
        number: 1,
        title: "Let You Down",
        duration: "25m",
        overview: "David Martinez struggles to afford his academy fees while his overworked mother pushes him to succeed in a ruthless Night City.",
        thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80"
      },
      {
        id: "cp-e2",
        season: 1,
        number: 2,
        title: "Like a Boy",
        duration: "24m",
        overview: "With high-grade military cyberware implanted in his spine, David seeks retribution on his bullies before meeting the enigmatic Lucy.",
        thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=500&q=80"
      }
    ]
  },
  {
    id: "squid-game",
    title: "Squid Game",
    type: "series",
    logoTitle: "SQUID GAME",
    backdrop: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    matchScore: 97,
    rating: "18+",
    releaseYear: 2024,
    seasons: 2,
    seasonsCount: 2,
    resolution: "4K Ultra HD",
    audio: "5.1 Surround",
    isTop10: 3,
    isTrending: true,
    isPopular: true,
    genres: ["Thriller", "Drama", "Suspense"],
    tags: ["High-stakes", "Tense", "Dark"],
    overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting 45.6 billion-won prize awaits with deadly high stakes.",
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon", "Jung Ho-yeon"],
    creator: "Hwang Dong-hyuk",
    episodes: [
      {
        id: "sg-s1e1",
        season: 1,
        number: 1,
        title: "Red Light, Green Light",
        duration: "60m",
        overview: "Hoping to win easy cash, a desperate Gi-hun agrees to play an enigmatic game. Soon, contestants realize what failure truly means.",
        thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=500&q=80"
      },
      {
        id: "sg-s1e2",
        season: 1,
        number: 2,
        title: "Hell",
        duration: "63m",
        overview: "Split between continuing the tournament or returning to their destitute lives, the survivors hold a vote.",
        thumbnail: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=500&q=80"
      }
    ]
  },
  {
    id: "inception",
    title: "Inception",
    type: "movie",
    logoTitle: "INCEPTION",
    backdrop: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    matchScore: 96,
    rating: "13+",
    releaseYear: 2010,
    duration: "2h 28m",
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos 7.1",
    isTop10: 4,
    isTrending: true,
    isPopular: false,
    genres: ["Sci-Fi", "Action", "Psychological Thriller"],
    tags: ["Mind-Bending", "Complex", "Masterpiece"],
    overview: "A skilled thief is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    creator: "Christopher Nolan"
  },
  {
    id: "the-witcher",
    title: "The Witcher",
    type: "series",
    logoTitle: "THE WITCHER",
    backdrop: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    matchScore: 95,
    rating: "18+",
    releaseYear: 2023,
    seasons: 3,
    seasonsCount: 3,
    resolution: "4K Ultra HD",
    audio: "5.1 Audio",
    isTop10: 5,
    isTrending: false,
    isPopular: true,
    genres: ["Fantasy", "Action", "Adventure"],
    tags: ["Epic", "Dark Fantasy", "Monsters"],
    overview: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan", "Joey Batey"],
    creator: "Lauren Schmidt Hissrich",
    episodes: [
      {
        id: "tw-s1e1",
        season: 1,
        number: 1,
        title: "The End's Beginning",
        duration: "61m",
        overview: "Hostile townsfolk and a cunning mage greet Geralt in the town of Blaviken. Ciri finds her royal world upended as Nilfgaard sets its sights on Cintra.",
        thumbnail: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=500&q=80"
      }
    ]
  },
  {
    id: "arcane",
    title: "Arcane: League of Legends",
    type: "series",
    logoTitle: "ARCANE",
    backdrop: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    matchScore: 99,
    rating: "16+",
    releaseYear: 2024,
    seasons: 2,
    seasonsCount: 2,
    resolution: "4K Ultra HD",
    audio: "Spatial Audio",
    isTop10: 6,
    isTrending: true,
    isPopular: true,
    genres: ["Animation", "Sci-Fi", "Action", "Fantasy"],
    tags: ["Stylized", "Emotional", "Acclaimed"],
    overview: "Amid the conflict between the twin cities of Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    cast: ["Hailee Steinfeld", "Ella Purnell", "Kevin Alejandro", "Katie Leung"],
    creator: "Christian Linke, Alex Yee",
    episodes: [
      {
        id: "arc-e1",
        season: 1,
        number: 1,
        title: "Welcome to the Playground",
        duration: "43m",
        overview: "Orphan sisters Vi and Powder undertake a heist in Piltover's topside that goes dangerously awry.",
        thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=500&q=80"
      }
    ]
  },
  {
    id: "interstellar",
    title: "Interstellar",
    type: "movie",
    logoTitle: "INTERSTELLAR",
    backdrop: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    matchScore: 98,
    rating: "13+",
    releaseYear: 2014,
    duration: "2h 49m",
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos",
    isTop10: 7,
    isTrending: true,
    isPopular: true,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    tags: ["Cosmic", "Visionary", "Tearjerker"],
    overview: "With humanity facing extinction on a dying Earth, a group of astronauts travel through a mysterious wormhole near Saturn in search of a new home for mankind.",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    creator: "Christopher Nolan"
  },
  {
    id: "peaky-blinders",
    title: "Peaky Blinders",
    type: "series",
    logoTitle: "PEAKY BLINDERS",
    backdrop: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    matchScore: 97,
    rating: "18+",
    releaseYear: 2022,
    seasons: 6,
    seasonsCount: 6,
    resolution: "HD",
    audio: "5.1 Audio",
    isTop10: 8,
    isTrending: false,
    isPopular: true,
    genres: ["Crime", "Period Drama", "Thriller"],
    tags: ["Gritty", "Ruthless", "Sharp"],
    overview: "A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost.",
    cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory", "Tom Hardy"],
    creator: "Steven Knight"
  },
  {
    id: "the-queens-gambit",
    title: "The Queen's Gambit",
    type: "series",
    logoTitle: "THE QUEEN'S GAMBIT",
    backdrop: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    matchScore: 98,
    rating: "16+",
    releaseYear: 2020,
    seasons: 1,
    seasonsCount: 1,
    resolution: "4K Ultra HD",
    audio: "5.1 Audio",
    isTop10: 9,
    isTrending: false,
    isPopular: true,
    genres: ["Drama", "Period", "Psychological"],
    tags: ["Cerebral", "Intimate", "Triumph"],
    overview: "Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA. But child stardom comes at a steep price.",
    cast: ["Anya Taylor-Joy", "Bill Camp", "Marielle Heller", "Thomas Brodie-Sangster"],
    creator: "Scott Frank, Allan Scott"
  },
  {
    id: "dark",
    title: "Dark",
    type: "series",
    logoTitle: "DARK",
    backdrop: "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    matchScore: 99,
    rating: "16+",
    releaseYear: 2020,
    seasons: 3,
    seasonsCount: 3,
    resolution: "4K Ultra HD",
    audio: "5.1 Audio",
    isTop10: 10,
    isTrending: true,
    isPopular: false,
    genres: ["Sci-Fi", "Mystery", "Thriller"],
    tags: ["Complex", "Chilling", "Time-Travel"],
    overview: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations in a German town.",
    cast: ["Louis Hofmann", "Oliver Masucci", "Jördis Triebel", "Maja Schöne"],
    creator: "Baran bo Odar, Jantje Friese"
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    type: "movie",
    logoTitle: "BLADE RUNNER 2049",
    backdrop: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    matchScore: 95,
    rating: "16+",
    releaseYear: 2017,
    duration: "2h 44m",
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos",
    isTop10: null,
    isTrending: false,
    isPopular: true,
    genres: ["Sci-Fi", "Action", "Mystery"],
    tags: ["Atmospheric", "Noir", "Philosophical"],
    overview: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks"],
    creator: "Denis Villeneuve"
  },
  {
    id: "wednesday",
    title: "Wednesday",
    type: "series",
    logoTitle: "WEDNESDAY",
    backdrop: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    matchScore: 94,
    rating: "13+",
    releaseYear: 2023,
    seasons: 1,
    seasonsCount: 1,
    resolution: "4K Ultra HD",
    audio: "5.1 Audio",
    isTop10: null,
    isTrending: true,
    isPopular: true,
    genres: ["Comedy", "Mystery", "Fantasy"],
    tags: ["Quirky", "Gothic", "Deadpan"],
    overview: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome", "Christina Ricci"],
    creator: "Alfred Gough, Miles Millar"
  },
  {
    id: "glass-onion",
    title: "Glass Onion: A Knives Out Mystery",
    type: "movie",
    logoTitle: "GLASS ONION",
    backdrop: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    matchScore: 92,
    rating: "13+",
    releaseYear: 2022,
    duration: "2h 19m",
    resolution: "4K Ultra HD",
    audio: "Dolby Atmos",
    isTop10: null,
    isTrending: false,
    isPopular: true,
    genres: ["Comedy", "Mystery", "Crime"],
    tags: ["Witty", "Twisty", "Ensemble"],
    overview: "Master detective Benoit Blanc travels to Greece to peel back the layers of a mystery involving a tech billionaire and his eclectic group of friends.",
    cast: ["Daniel Craig", "Edward Norton", "Janelle Monáe", "Kathryn Hahn"],
    creator: "Rian Johnson"
  },
  {
    id: "black-mirror",
    title: "Black Mirror",
    type: "series",
    logoTitle: "BLACK MIRROR",
    backdrop: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    matchScore: 96,
    rating: "18+",
    releaseYear: 2023,
    seasons: 6,
    seasonsCount: 6,
    resolution: "4K Ultra HD",
    audio: "5.1 Audio",
    isTop10: null,
    isTrending: false,
    isPopular: true,
    genres: ["Sci-Fi", "Thriller", "Satire"],
    tags: ["Dystopian", "Chilling", "Twisted"],
    overview: "This sci-fi anthology series explores a twisted, high-tech near-future where humanity's greatest innovations and darkest instincts collide.",
    cast: ["Jesse Plemons", "Bryce Dallas Howard", "Aaron Paul", "Salma Hayek"],
    creator: "Charlie Brooker"
  },
  {
    id: "money-heist",
    title: "Money Heist (La Casa de Papel)",
    type: "series",
    logoTitle: "LA CASA DE PAPEL",
    backdrop: "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1920&q=80",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    matchScore: 97,
    rating: "18+",
    releaseYear: 2021,
    seasons: 5,
    seasonsCount: 5,
    resolution: "HD",
    audio: "5.1 Audio",
    isTop10: null,
    isTrending: true,
    isPopular: true,
    genres: ["Crime", "Heist", "Action", "Thriller"],
    tags: ["Suspenseful", "Heart-Pounding", "Intense"],
    overview: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
    cast: ["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño", "Pedro Alonso"],
    creator: "Álex Pina"
  }
];

// Profile data
export const profiles = [
  {
    id: "profile-1",
    name: "Alex",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    isKids: false
  },
  {
    id: "profile-2",
    name: "Kids",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80",
    isKids: true
  },
  {
    id: "profile-3",
    name: "Guest",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80",
    isKids: false
  }
];

// Featured Hero billboard item
export const heroFeaturedItem = catalog.find(item => item.id === "stranger-things");
